// Generated by npm run build. Edit src/ and scripts/build.js.
'use strict';

// Shared static catalog. No credentials, imports, or account discovery at runtime.
const KazujiCatalog = (() => {
  const profiles = [
    {id:'4k',name:'4K',quality:2160,enabled:true},
    {id:'full-hd',name:'Full HD',quality:1080,enabled:true},
    {id:'hd',name:'HD',quality:720,enabled:true},
    {id:'sd',name:'SD',quality:480,enabled:true},
    {id:'unknown',name:'Qualidade desconhecida',quality:0,enabled:false},
  ];
  const sources = [
    ['frost','Frost Stream','https://froststream.cloutteam.com','direct',true],
    ['fenix','Fenix Flix','https://fenixflix.fenixhub.online/configure','direct',false],
    ['kingvod','King Vod','https://da5f663b4690-kingvod.baby-beamup.club/manifest.json','direct',true],
    ['bscine','BsCine','https://bscine.alwaysdata.net/manifest.json','direct',true],
    ['popplay','Pop Play','https://site--popplay--rg2h4m5nr425.code.run/manifest.json','direct',true],
    ['mico','Mico-Leão Dublado','https://27a5b2bfe3c0-stremio-brazilian-addon.baby-beamup.club/manifest.json','direct',true],
    ['bestcine','BestCine','https://bestcine.dpdns.org/','direct',false],
    ['superstream','SuperStream','https://da5f663b4690-superstream.baby-beamup.club','direct',false],
    ['zeus','Zeus','https://398fe185fed6-zeus.baby-beamup.club/v1-p1kv-q27','direct',true],
    ['saimuel','Saimuel','https://saimuelptbr-how6fvsx.manus.space','configured',false],
    ['unioflix','UnioFlix','https://bcf125302240-unioflix.baby-beamup.club','direct',true],
    ['betor','BeTor','https://stremio-betor.onrender.com/','torrent',false],
    ['nyaa','Nyaa Anime BR','https://stremio-br-anime.onrender.com/manifest.json','configured',false],
    ['indexabr','Indexa Br','https://indexabr.vercel.app','configured',false],
    ['brasilrd','BrasilRD','https://brasil-rd-oficial.oniko.org/configure','configured',false],
    ['brazuca','Brazuca Torrents','https://94c8cb9f702d-brazuca-torrents.baby-beamup.club','torrent',false],
    ['torrentio','Torrentio','https://torrentio.strem.fun/providers=comando,bludv,micoleaodublado%7Clanguage=portuguese/manifest.json','torrent',false],
    ['magneto','Magneto','https://magneto-jnv5.onrender.com/v1/configure','configured',false],
    ['prowjack','ProwJack','https://prowjack-delta.vercel.app/configure','configured',false],
    ['pengu','Pengu','https://pengu.uk/configure','configured',false],
    ['mediafusion','Media Fusion','https://mediafusion.elfhosted.com/app/configure','configured',false],
    ['piratebay','ThePirateBay','https://thepiratebay-plus.strem.fun/manifest.json','torrent',false],
    ['meteor','Meteor','https://meteorfortheweebs.midnightignite.me/configure','configured',false],
    ['corsaro','Corsaro Viola','https://icv.stremio-italia.eu/configure','torrent',false],
    ['comet','Comet','https://comet.elfhosted.com/configure','configured',false],
    ['orion','Orion','https://5a0d1888fa64-orion.baby-beamup.club/configure','configured',false],
    ['torrentsdb','TorrentsDB','https://torrentsdb.com/configure','torrent',false],
    ['jackettio','Jackettio','https://jackettio.elfhosted.com/configure','configured',false],
    ['pipe','Pipe','https://pipe.boringways.workers.dev','torrent',false],
    ['nexus','Nexus','https://nexuszen.vercel.app','direct',true],
  ].map(([id,name,url,kind,enabled]) => ({id,name,url,kind,enabled,
    // Configuration pages are kept as links, never queried as stream manifests.
    manifest:kind==='configured'?null:url.replace(/\/configure\/?$/,'').replace(/\/$/,'')+(url.endsWith('/manifest.json')?'':'/manifest.json'),
  }));
  const isOn = value => value===true || value==='true';
  function applySources(settings,normalize) {
    const config=Object.assign({},settings);
    const urls=normalize({manifests:settings.manifests}).manifests;
    if(settings.useBuiltInSources==null || settings.useBuiltInSources==='' || isOn(settings.useBuiltInSources)) {
      for(const source of sources) {
        const custom=String(settings['sourceManifest_'+source.id]||'').trim();
        const value=settings['sourceEnabled_'+source.id];
        const enabled=value==null || value==='' ? !!custom || source.enabled || (source.kind==='torrent' && !!String(settings.torboxApiKey||'').trim()) : isOn(value);
        if(!enabled)continue;
        if(source.kind==='torrent' && !custom && !String(settings.torboxApiKey||'').trim())continue;
        if(custom) urls.push(...normalize({manifests:custom}).manifests);
        else if(source.manifest) urls.push(source.manifest);
      }
    }
    config.manifests=[...new Set(urls)];
    return config;
  }
  return {profiles,sources,applySources};
})();
if(typeof module!=='undefined')module.exports=KazujiCatalog;

'use strict';

// Direct TorBox API adapter for QuickJS. Credentials stay in local settings.
const KazujiTorBox = (() => {
  const API='https://api.torbox.app/v1/api/torrents/';
  function hashOf(stream) {
    const resolve=stream.clientResolve||{},raw=resolve.stream && resolve.stream.raw || {};
    let hash=String(stream.infoHash || resolve.infoHash || raw.infoHash || '').trim();
    if(!hash) {
      const match=/[?&]xt=urn(?::|%3a)btih(?::|%3a)([a-f0-9]{40}|[a-z2-7]{32})(?:&|$)/i.exec(stream.url||'');
      if(match)hash=match[1];
    }
    if(/^[a-f0-9]{40}$/i.test(hash))return hash.toLowerCase();
    if(!/^[a-z2-7]{32}$/i.test(hash))return '';
    const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
    let bits=0,value=0,out='';
    for(const ch of hash.toUpperCase()) {
      value=(value<<5)|alphabet.indexOf(ch);bits+=5;
      if(bits>=8){bits-=8;out+=((value>>>bits)&255).toString(16).padStart(2,'0');}
    }
    return out;
  }
  const nameOf=file=>String(file.name||file.short_name||file.shortName||file.absolute_path||'');
  const basename=name=>String(name).replace(/\\/g,'/').split('/').pop().toLowerCase();
  const video=file=>/\.(mkv|mp4|avi|mov|m4v|webm|ts|m2ts)$/i.test(nameOf(file)) && !/\b(sample|trailer|preview)\b/i.test(basename(nameOf(file)));
  function episodeMatches(file,ctx) {
    const name=nameOf(file);
    const patterns=[/\bs(\d{1,3})[ ._-]*e(\d{1,3})(?!\d)/ig,/\b(\d{1,3})x(\d{1,3})(?!\d)/ig];
    return patterns.some(re=>{let match;while((match=re.exec(name)))if(Number(match[1])===ctx.season && Number(match[2])===ctx.episode)return true;return false;});
  }
  function selectFile(files,stream,ctx) {
    if(!Array.isArray(files))return null;
    const usable=files.filter(f=>f && Number.isInteger(f.id) && f.id>=0 && video(f));
    const filename=stream.behaviorHints && stream.behaviorHints.filename || stream.filename || '';
    if(filename) {
      const exact=usable.filter(f=>basename(nameOf(f))===basename(filename));
      if(exact.length===1 && (ctx.type!=='series' || episodeMatches(exact[0],ctx)))return exact[0];
    }
    // Stremio fileIdx is a zero-based torrent index, not the TorBox file ID.
    if(stream.fileIdx!=null) {
      const index=Number(stream.fileIdx),file=Number.isInteger(index) && index>=0?files[index]:null;
      if(file && usable.includes(file) && (ctx.type!=='series' || episodeMatches(file,ctx)))return file;
    }
    if(ctx.type==='series') {
      const episodes=usable.filter(f=>episodeMatches(f,ctx));
      return episodes.length===1?episodes[0]:null;
    }
    return usable.slice().sort((a,b)=>(Number(b.size)||0)-(Number(a.size)||0))[0]||null;
  }
  function createResolver({apiKey,quality,eligible,maxResolutions=4,concurrency=2,warn=()=>{}}) {
    apiKey=String(apiKey||'').trim();
    const cache=new Map(),torrents=new Map(),links=new Map(),waiting=[];
    let active=0,used=0,disabled=false,notified=false;
    const limit=Math.min(12,Math.max(1,Number(maxResolutions)||4));
    const slots=Math.min(3,Math.max(1,Number(concurrency)||2));
    function drain(){while(active<slots && waiting.length){active++;waiting.shift()();}}
    async function scheduled(work) {
      await new Promise(resolve=>{waiting.push(resolve);drain();});
      try{return await work();}finally{active--;drain();}
    }
    async function call(path,request,options={}) {
      if(disabled)throw new Error('TorBox indisponível');
      const response=await request(API+path,{...options,headers:{Accept:'application/json',Authorization:'Bearer '+apiKey,...options.headers},maxBytes:1048576});
      if(response.status===401 || response.status===403 || response.status===429)disabled=true;
      if(response.status<200 || response.status>=300 || response.truncated)throw new Error('Resposta TorBox inválida');
      const body=JSON.parse(response.text);
      if(body.success!==true || body.error || body.data==null)throw new Error('TorBox não resolveu a fonte');
      return body.data;
    }
    async function getTorrent(hash,request) {
      if(!torrents.has(hash))torrents.set(hash,scheduled(async()=>{
        if(used>=limit || disabled)return null;
        used++;
        const boundary='KazujiTorBox'+hash;
        const fields={magnet:'magnet:?xt=urn:btih:'+hash,add_only_if_cached:'true',allow_zip:'false',seed:'3'};
        const body=Object.entries(fields).map(([key,value])=>'--'+boundary+'\r\nContent-Disposition: form-data; name="'+key+'"\r\n\r\n'+value+'\r\n').join('')+'--'+boundary+'--\r\n';
        const created=await call('createtorrent',request,{method:'POST',headers:{'Content-Type':'multipart/form-data; boundary='+boundary},body});
        const id=created.torrent_id ?? created.id;
        if(!Number.isInteger(id) || id<0)return null;
        const data=await call('mylist?id='+id+'&bypass_cache=true',request);
        const torrent=Array.isArray(data)?data.find(t=>t.id===id):data;
        if(!torrent || torrent.id!==id || hashOf({infoHash:torrent.hash})!==hash)return null;
        return torrent;
      }).catch(()=>null));
      return torrents.get(hash);
    }
    async function resolveStreams(streams,{ctx,config,request}) {
      const isDirect=s=>s && /^https?:\/\//i.test(s.url||'') && !/\.torrent(?:[?#]|$)/i.test(s.url||'');
      const direct=streams.filter(isDirect);
      if(!apiKey || disabled)return direct;
      const candidates=streams.filter(s=>s && !isDirect(s) && hashOf(s) && config.qualities.includes(quality(s)) && (!eligible || eligible(s,config)));
      const hashes=[...new Set(candidates.map(hashOf))].slice(0,100);
      const missing=hashes.filter(hash=>!cache.has(hash));
      if(missing.length) {
        // One cache query per source batch; duplicate hashes share the same promise.
        const lookup=call('checkcached?format=object&list_files=true',request,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({hashes:missing})});
        for(const hash of missing)cache.set(hash,lookup.then(data=>data && !Array.isArray(data) && Object.keys(data).some(key=>key.toLowerCase()===hash && data[key] && typeof data[key]==='object')).catch(()=>false));
      }
      const resolved=await Promise.all(candidates.map(async stream=>{
        const hash=hashOf(stream);
        if(!cache.has(hash) || !await cache.get(hash))return null;
        const torrent=await getTorrent(hash,request);
        if(!torrent)return null;
        const file=selectFile(torrent.files,stream,ctx);
        if(!file)return null;
        const fileQuality=quality({behaviorHints:{filename:nameOf(file)}});
        if(fileQuality && !config.qualities.includes(fileQuality))return null;
        const key=torrent.id+':'+file.id;
        if(!links.has(key))links.set(key,scheduled(()=>call('requestdl?token='+encodeURIComponent(apiKey)+'&torrent_id='+torrent.id+'&file_id='+file.id+'&zip_link=false&redirect=false&append_name=false',request)).catch(()=>null));
        const url=await links.get(key);
        if(typeof url!=='string' || !/^https:\/\//i.test(url))return null;
        const result={...stream,url,quality:fileQuality || stream.quality,behaviorHints:{...stream.behaviorHints,filename:nameOf(file),videoSize:Number(file.size)||undefined}};
        // Playback uses only the signed HTTP link and never upstream auth headers.
        delete result.infoHash;delete result.fileIdx;delete result.sources;delete result.clientResolve;delete result.headers;
        delete result.behaviorHints.proxyHeaders;
        return result;
      }));
      if(disabled && !notified){notified=true;warn('TorBox indisponível: confira a chave, o plano ou o limite de requisições. Fontes HTTP continuam disponíveis.');}
      return direct.concat(resolved.filter(Boolean));
    }
    return resolveStreams;
  }
  return {hashOf,selectFile,createResolver};
})();
if(typeof module!=='undefined')module.exports=KazujiTorBox;

'use strict';

// Pure JavaScript: shared by Node and Nuvio QuickJS. No Node/browser imports.
const DEFAULTS = {
  manifests: [], qualities: [2160, 1080, 720, 480], languages: ['pt-BR'],
  languageMode: 'prefer', allowUnknownLanguage: true,
  resultMode: 'per_language', resultsPerGroup: 1,
  allowedCodecs: [], hdrMode: 'any', allowUnknownCompatibility: true,
  country: 'BR', allowedRatings: [], unknownRating: 'block',
  totalTimeoutMs: 6500, settleMs: 650, requestTimeoutMs: 2200, probeTimeoutMs: 1400,
  sourceConcurrency: 8, probeConcurrency: 4, maxCandidates: 48, maxProbes: 24,
  sampleBytes: 262144, probeMode: 'sample', allowUnverified: false,
  minMbps: {2160: 20, 1080: 6, 720: 3, 480: 1, 0: 1},
  torrentMode: 'off', tmdbApiKey: '',
};

function list(value) {
  if (Array.isArray(value)) return value;
  if (typeof value !== 'string' || !value.trim()) return [];
  if (value.trim()[0] === '[') {
    try { const parsed = JSON.parse(value); if (Array.isArray(parsed)) return parsed; } catch (_) {}
    throw new Error('Lista JSON inválida');
  }
  return value.split(/[\n,;]+/).map(x => x.trim()).filter(Boolean);
}
function manifestList(value) {
  if(typeof value!=='string' || value.trim().startsWith('['))return list(value);
  // Commas/semicolons are legal inside configured addon URLs (e.g. Torrentio
  // qualityfilter). Only split them when the next item starts a new HTTP URL.
  return value.split(/[\r\n]+|[,;](?=\s*https?:\/\/)/i).map(x=>x.trim()).filter(Boolean);
}
function number(value, fallback, min, max) {
  const n = value === '' || value == null ? NaN : Number(value);
  return Number.isFinite(n) ? Math.min(max, Math.max(min, Math.floor(n))) : fallback;
}
function bool(value, fallback) { return value == null ? fallback : value === true || value === 'true'; }
function enumValue(value, values, fallback) {
  if (value == null || value === '') return fallback;
  if (!values.includes(value)) throw new Error('Opção inválida: ' + value);
  return value;
}
// Nuvio's URL polyfill does not synchronize pathname/search edits with href.
// Assemble URLs explicitly and resolve HLS relatives without browser URL semantics.
function parseHttpUrl(raw) {
  const value=String(raw).trim();
  const match=/^(https?):\/\/([^/?#]+)([^?#]*)(\?[^#]*)?(?:#.*)?$/i.exec(value);
  if(!match || /[\s\\\x00-\x1f]/.test(value) || match[2].includes('@'))throw new Error('URL HTTP(S) inválida');
  return {protocol:match[1].toLowerCase()+':',origin:match[1].toLowerCase()+'://'+match[2],pathname:match[3]||'/',search:match[4]||''};
}
function pathWithoutDots(path) {
  const parts=path.split('/'),out=[];
  for(const part of parts){if(part==='..'){if(out.length>1)out.pop();}else if(part!=='.')out.push(part);}
  if(['.','..'].includes(parts[parts.length-1]))out.push('');
  return out.join('/')||'/';
}
function resolveHttpUrl(raw,base) {
  raw=String(raw).trim();
  if(/^https?:\/\//i.test(raw)){const u=parseHttpUrl(raw);return u.origin+pathWithoutDots(u.pathname)+u.search;}
  const b=parseHttpUrl(base);
  if(raw.startsWith('//'))return resolveHttpUrl(b.protocol+raw);
  if(/^[a-z][a-z0-9+.-]*:/i.test(raw))throw new Error('Protocolo não permitido');
  raw=raw.split('#')[0];
  if(!raw)return b.origin+b.pathname+b.search;
  if(raw.startsWith('?'))return b.origin+b.pathname+raw;
  const query=raw.indexOf('?'),path=query<0?raw:raw.slice(0,query),search=query<0?'':raw.slice(query);
  return b.origin+pathWithoutDots(path.startsWith('/')?path:b.pathname.replace(/[^/]*$/,'')+path)+search;
}
function normalizeConfig(input) {
  input = input || {};
  const config = Object.assign({}, DEFAULTS, input);
  config.manifests = [...new Set(manifestList(input.manifests).map(raw => {
    const url = parseHttpUrl(raw);
    if (!url.pathname.endsWith('/manifest.json')) url.pathname = url.pathname.replace(/\/$/, '') + '/manifest.json';
    return url.origin+url.pathname+url.search;
  }))];
  if (config.manifests.length > 64) throw new Error('Máximo de 64 manifestos');
  config.qualities = [...new Set(list(input.qualities == null || input.qualities === '' ? DEFAULTS.qualities : input.qualities).map(x => {
    const q = /^(4k|uhd)$/i.test(String(x)) ? 2160 : Number(String(x).replace(/p$/i, ''));
    if (![2160,1080,720,480,0].includes(q)) throw new Error('Qualidade inválida');
    return q;
  }))].sort((a,b) => b-a);
  if (!config.qualities.length) throw new Error('Selecione ao menos uma qualidade');
  config.languages = list(input.languages == null || input.languages === '' ? DEFAULTS.languages : input.languages).map(language).filter(Boolean);
  config.resultMode = enumValue(input.resultMode, ['per_language','per_quality','all'], 'per_language');
  config.resultsPerGroup = number(input.resultsPerGroup, 1, 1, 20);
  config.allowedCodecs = [...new Set(list(input.allowedCodecs).map(codec))];
  if (config.allowedCodecs.some(x=>!x)) throw new Error('Codec inválido: use h264, hevc ou av1');
  config.hdrMode = enumValue(input.hdrMode, ['any','sdr','no_dolby_vision'], 'any');
  config.allowUnknownCompatibility = bool(input.allowUnknownCompatibility, true);
  config.allowedRatings = [...new Set(list(input.allowedRatings).map(x => String(x).trim().toUpperCase()))];
  config.country = String(input.country || 'BR').toUpperCase();
  if (!/^[A-Z]{2}$/.test(config.country)) throw new Error('País deve usar ISO de duas letras');
  config.languageMode = enumValue(input.languageMode, ['prefer','strict','any'], 'prefer');
  config.unknownRating = enumValue(input.unknownRating, ['block','allow'], 'block');
  config.probeMode = enumValue(input.probeMode, ['sample','head','off'], 'sample');
  config.torrentMode = enumValue(input.torrentMode, ['off','native'], 'off');
  config.allowUnknownLanguage = bool(input.allowUnknownLanguage, true);
  config.allowUnverified = bool(input.allowUnverified, false);
  for (const [key,min,max] of [
    ['totalTimeoutMs',500,20000],['settleMs',0,3000],['requestTimeoutMs',100,8000],
    ['probeTimeoutMs',100,5000],['sourceConcurrency',1,12],['probeConcurrency',1,8],
    ['maxCandidates',1,200],['maxProbes',1,100],['sampleBytes',32768,524288],
  ]) config[key] = number(input[key], DEFAULTS[key], min, max);
  config.minMbps = Object.assign({}, DEFAULTS.minMbps);
  if (input.minMbps && typeof input.minMbps === 'object') for (const q of config.qualities) {
    const n = Number(input.minMbps[q]);
    if (Number.isFinite(n) && n >= 0 && n <= 500) config.minMbps[q] = n;
  }
  config.tmdbApiKey = String(input.tmdbApiKey || '').trim();
  return config;
}

function language(raw) {
  const s = String(raw || '').trim().toLowerCase().replace(/_/g,'-');
  const aliases = {por:'pt',portuguese:'pt',portugues:'pt',eng:'en',english:'en',spa:'es',spanish:'es',jpn:'ja',japanese:'ja',fra:'fr',fre:'fr',french:'fr',deu:'de',ger:'de',german:'de',ita:'it',rus:'ru',hin:'hi',pob:'pt-BR',ptbr:'pt-BR',brazilian:'pt-BR','pt-br':'pt-BR'};
  return aliases[s] || (/^[a-z]{2,3}(-[a-z]{2})?$/.test(s) ? s : '');
}
function audioLanguages(stream) {
  const parsed = parsedStream(stream);
  const explicit = list(stream.languages || stream.language || stream.audioLanguages || parsed.languages || []);
  const result = explicit.map(language).filter(Boolean);
  const text = releaseText(stream).toLowerCase();
  for (const [regex,code] of [
    [/\b(pt[ ._-]?br|pob|brazilian|portugu[eê]s brasileiro|dublado)\b/, 'pt-BR'],
    [/\b(portugu[eê]s|portuguese|por|pt)\b/,'pt'], [/\b(english|eng|en)\b/,'en'],
    [/\b(spanish|espa[nñ]ol|spa|es)\b/,'es'], [/\b(japanese|jpn|ja)\b/,'ja'],
    [/\b(french|fra|fre|fr)\b/,'fr'], [/\b(german|ger|deu|de)\b/,'de'],
    [/\b(italian|ita|it)\b/,'it'], [/\b(russian|rus|ru)\b/,'ru'],
  ]) if (regex.test(text)) result.push(code);
  // Subtitles and original_language are intentionally not evidence of audio tracks.
  return [...new Set(result)].filter(x=>x!=='pt' || !result.includes('pt-BR'));
}
function codec(raw) {
  const s=String(raw||'').toLowerCase().replace(/[ ._-]/g,'');
  return /^(h264|x264|avc|avc1)$/.test(s)?'h264':/^(h265|x265|hevc|hev1|hvc1)$/.test(s)?'hevc':/^(av1|av01)$/.test(s)?'av1':'';
}
function compatibility(stream) {
  const parsed=parsedStream(stream);
  const text=[stream.codec,stream.videoCodec,stream.hdr,stream.dynamicRange,parsed.codec,parsed.hdr,releaseText(stream)].filter(Boolean).join(' ');
  const videoCodec=codec(stream.videoCodec||stream.codec) || (/\b(h[ ._-]?264|x264|avc)\b/i.test(text)?'h264':/\b(h[ ._-]?265|x265|hevc)\b/i.test(text)?'hevc':/\bav1\b/i.test(text)?'av1':'');
  const range=/\b(dolby[ ._-]?vision|dovi|dv)\b/i.test(text)?'dv':stream.hdr===true || /\b(hdr(?:10\+?)?|hlg)\b/i.test(text)?'hdr':stream.hdr===false || /\bsdr\b/i.test(text)?'sdr':'';
  return {codec:videoCodec,range};
}
function compatibilityAllowed(info,config) {
  if (config.allowedCodecs.length && (info.codec ? !config.allowedCodecs.includes(info.codec) : !config.allowUnknownCompatibility)) return false;
  if (config.hdrMode!=='any') {
    if (!info.range) return config.allowUnknownCompatibility;
    if (config.hdrMode==='sdr' && info.range!=='sdr' || config.hdrMode==='no_dolby_vision' && info.range==='dv') return false;
  }
  return true;
}
function reportedSpeed(stream) {
  // Only fields with explicit Mbps units; arbitrary "speed" values are ambiguous.
  const value=stream.speedMbps ?? stream.downloadSpeedMbps;
  const n=typeof value==='number'?value:NaN;
  return Number.isFinite(n) && n>0 && n<=10000?n:0;
}
function quality(stream) {
  if (stream.quality != null) {
    const declared=String(stream.quality).trim();
    if (/^(2160p?|4k|uhd)$/i.test(declared)) return 2160;
    if (/^(1080|720|480)p?$/i.test(declared)) return Number(declared.replace(/p$/i,''));
  }
  const parsed=parsedStream(stream);
  const s = [stream.quality,parsed.resolution,releaseText(stream)].filter(Boolean).join(' ');
  if (/\b(2160p?|4k|uhd)\b/i.test(s)) return 2160;
  for (const q of [1080,720,480]) if (new RegExp('\\b'+q+'p?\\b','i').test(s)) return q;
  return 0;
}
function httpUrl(raw) { try {parseHttpUrl(raw);return true;} catch (_) {return false;} }
function safeHeaders(raw) {
  const out = {};
  if (!raw || typeof raw !== 'object') return out;
  for (const key of Object.keys(raw)) {
    const value = String(raw[key]);
    if (!/^[!#$%&'*+.^_`|~0-9A-Za-z-]+$/.test(key) || /[\r\n]/.test(value)) continue;
    if (/^(range|host|connection|content-length|transfer-encoding)$/i.test(key)) continue;
    out[key] = value;
  }
  return out;
}
function supports(manifest,type,id) {
  const resources = Array.isArray(manifest.resources) ? manifest.resources : [];
  const stream = resources.find(x => x === 'stream' || (x && x.name === 'stream'));
  if (!stream) return false;
  const types = typeof stream === 'object' && stream.types || manifest.types || [];
  const prefixes = typeof stream === 'object' && stream.idPrefixes || manifest.idPrefixes || [];
  return types.includes(type) && (!prefixes.length || prefixes.some(p => id.startsWith(p)));
}
function resourceUrl(manifestUrl,type,id) {
  const url = parseHttpUrl(manifestUrl);
  url.pathname = url.pathname.replace(/manifest\.json$/, 'stream/'+encodeURIComponent(type)+'/'+encodeURIComponent(id)+'.json');
  return url.origin+url.pathname+url.search;
}
function parseInput(raw,type,season,episode) {
  type = type === 'series' || type === 'tv' ? 'series' : type === 'movie' ? 'movie' : '';
  if (!type) throw new Error('Tipo não suportado');
  const parts = String(raw).replace(/^tmdb[/:]/,'').split(':');
  const base = parts[0];
  if (!/^(tt\d+|\d+)$/.test(base)) throw new Error('ID deve ser TMDB ou IMDb');
  if (type === 'series') {
    season = season == null ? parts[1] : season;
    episode = episode == null ? parts[2] : episode;
    if (!/^\d+$/.test(String(season)) || !/^\d+$/.test(String(episode)) || Number(episode)<1) throw new Error('Temporada/episódio inválido');
  }
  return {base,type,tmdbId: /^\d+$/.test(base) ? base : null,imdbId: /^tt/.test(base) ? base : null,season:Number(season),episode:Number(episode)};
}
function streamId(ctx,prefix) {
  const base = prefix === 'tmdb:' ? ctx.tmdbId && 'tmdb:'+ctx.tmdbId : ctx.imdbId;
  return base && base + (ctx.type === 'series' ? ':'+ctx.season+':'+ctx.episode : '');
}
function ratingValues(meta,ctx,country) {
  if (ctx.type === 'movie') {
    const row = meta.release_dates && meta.release_dates.results && meta.release_dates.results.find(x=>x.iso_3166_1===country);
    return [...new Set((row && row.release_dates || []).map(x=>String(x.certification||'').trim().toUpperCase()).filter(Boolean))];
  }
  return (meta.content_ratings && meta.content_ratings.results || []).filter(x=>x.iso_3166_1===country).map(x=>String(x.rating||'').trim().toUpperCase()).filter(Boolean);
}
function ratingAllowed(values,config) {
  if (!config.allowedRatings.length) return true;
  if (!values.length) return config.unknownRating === 'allow';
  // Multiple conflicting certifications: require every one to be allowed.
  return values.every(x=>config.allowedRatings.includes(x));
}
function languageRank(langs,config) {
  if (config.languageMode === 'any' || !config.languages.length) return 0;
  let best = 1000;
  config.languages.forEach((want,i)=>langs.forEach(have=>{
    if (have === want) best = Math.min(best,i*2);
    else if (!want.includes('-') && have.split('-')[0] === want) best = Math.min(best,i*2+1);
  }));
  return best;
}
function candidate(stream,source,config,output) {
  if (!stream || typeof stream !== 'object') return null;
  const q = quality(stream);
  if (!config.qualities.includes(q)) return null;
  const langs = audioLanguages(stream), rank = languageRank(langs,config);
  const media=compatibility(stream);
  if (!compatibilityAllowed(media,config)) return null;
  if ((!langs.length && !config.allowUnknownLanguage) || (config.languageMode === 'strict' && rank===1000 && (langs.length || !config.allowUnknownLanguage))) return null;
  const hash = String(stream.infoHash || '').trim();
  const torrentUrl=/^magnet:|^torrent:\/\/|\.torrent(?:[?#]|$)/i.test(stream.url || '');
  const torrent = /^(?:[a-fA-F0-9]{40}|[A-Za-z2-7]{32})$/.test(hash) || torrentUrl;
  const direct = httpUrl(stream.url) && !torrentUrl;
  // Native output accepts HTTP video only. An optional resolver can convert
  // cached hashes to signed HTTP links before candidates are ingested.
  const deferred = !direct && (torrent || stream.clientResolve);
  if (deferred && (output !== 'stremio' || config.torrentMode !== 'native')) return null;
  if (!direct && !deferred) return null;
  const headers = safeHeaders(Object.assign({},stream.behaviorHints && stream.behaviorHints.proxyHeaders && stream.behaviorHints.proxyHeaders.request,stream.headers));
  const key = direct ? stream.url+'|'+JSON.stringify(Object.keys(headers).sort().map(k=>[k,headers[k]])) : hash+'|'+(stream.fileIdx ?? '')+'|'+(stream.url || '')+'|'+JSON.stringify(stream.clientResolve || {});
  const groupLanguage=langs.slice().sort((a,b)=>languageRank([a],config)-languageRank([b],config)||a.localeCompare(b))[0]||'und';
  return {raw:stream,source,q,langs,rank:langs.length?rank:1001,groupLanguage,media,reportedMbps:reportedSpeed(stream),headers,key,deferred,health:null};
}

function metadata(meta,ctx,config) {
  const clean=value=>String(value||'').replace(/[\r\n]+/g,' ').trim();
  const date=String(meta.release_date||meta.first_air_date||'');
  const directors=ctx.type==='series'?(meta.created_by||[]):(meta.credits && meta.credits.crew||[]).filter(x=>x.job==='Director');
  return {title:clean(meta.title||meta.name||meta.original_title||meta.original_name)||'Título não informado · '+ctx.base,
    year:/^\d{4}-/.test(date)?date.slice(0,4):'',
    creators:[...new Set(directors.map(x=>clean(x.name)).filter(Boolean))].join(', '),
    studios:[...new Set((meta.production_companies||[]).map(x=>clean(x.name)).filter(Boolean))].join(', '),
    ratings:ratingValues(meta,ctx,config.country),country:config.country,originalLanguage:language(meta.original_language)};
}
function selectResults(candidates,config) {
  const sorted=candidates.slice().sort((a,b)=>b.q-a.q || compare(a,b) || a.key.localeCompare(b.key));
  if(config.resultMode==='all')return sorted;
  const counts=new Map();
  return sorted.filter(c=>{
    const group=c.q+(config.resultMode==='per_language'?'|'+c.groupLanguage:'');
    const count=counts.get(group)||0;
    if(count>=config.resultsPerGroup)return false;
    counts.set(group,count+1);return true;
  });
}

// Only release metadata is evidence of technical properties. TMDB credits,
// subtitle languages, URL tokens and successful probes do not imply codec/HDR/audio.
function parsedStream(stream) {
  const resolve=stream.clientResolve || {};
  const raw=resolve.stream && resolve.stream.raw || {};
  return raw.parsed || {};
}
function releaseFilename(stream) {
  const resolve=stream.clientResolve || {},raw=resolve.stream && resolve.stream.raw || {};
  return [stream.behaviorHints && stream.behaviorHints.filename,stream.filename,raw.filename,resolve.filename]
    .find(x=>typeof x==='string' && x.trim()) || '';
}
function releaseText(stream) {
  const resolve=stream.clientResolve || {},raw=resolve.stream && resolve.stream.raw || {},parsed=parsedStream(stream);
  return [releaseFilename(stream),raw.torrentName,resolve.torrentName,parsed.rawTitle,parsed.parsedTitle,
    stream.name,stream.title,stream.description].filter(x=>typeof x==='string').join(' ');
}
function positiveBytes(value) {
  const n=typeof value==='number'?value:typeof value==='string' && /^\d+$/.test(value.trim())?Number(value):NaN;
  return Number.isSafeInteger(n) && n>0?n:undefined;
}
function streamSize(stream) {
  const resolve=stream.clientResolve || {},raw=resolve.stream && resolve.stream.raw || {};
  for(const value of [stream.behaviorHints && stream.behaviorHints.videoSize,stream.size,stream.fileSize,raw.size]) {
    const bytes=positiveBytes(value);if(bytes)return bytes;
  }
  // A formatted size is an approximate declaration, with explicit SI/IEC units.
  const text=[typeof stream.size==='string'?stream.size:'',stream.description,stream.title].filter(Boolean).join(' ');
  const match=/\b(\d+(?:[.,]\d+)?)\s*(KiB|MiB|GiB|TiB|KB|MB|GB|TB)\b/i.exec(text);
  if(!match)return undefined;
  const unit=match[2].toUpperCase(),power={K:1,M:2,G:3,T:4}[unit[0]];
  return positiveBytes(Math.round(Number(match[1].replace(',','.'))*Math.pow(unit.includes('I')?1024:1000,power)));
}
function sizeLabel(bytes) {
  const units=['B','KB','MB','GB','TB'];let value=bytes,i=0;
  while(value>=1000 && i<units.length-1){value/=1000;i++;}
  return (i?value.toFixed(2).replace(/\.?0+$/,''):String(value))+' '+units[i];
}
function fusionTags(c) {
  const s=c.raw,p=parsedStream(s);
  const text=[releaseText(s),s.source,p.quality,s.videoCodec,s.codec,p.codec,s.hdr,s.dynamicRange,p.hdr,
    s.audioCodec,s.audio,p.audio,s.channels,p.channels,s.edition,p.edition,s.bitDepth].filter(Boolean).join(' ');
  const tags=[];
  function first(patterns){for(const [pattern,label]of patterns)if(pattern.test(text)){tags.push(label);break;}}
  first([[/\bremux\b/i,'REMUX'],[/\b(?:blu[ ._-]?ray|b[dr]rip)\b/i,'BluRay'],[/\bweb[ ._-]?dl\b/i,'WEB-DL'],[/\bwebrip\b/i,'WEBRip'],[/\b(?:hdcam|camrip|cam)\b/i,'HDCAM'],[/\bdvdrip\b/i,'DVDRip']]);
  const declaredCodec=codec(s.videoCodec||s.codec||p.codec);
  if(declaredCodec)tags.push({h264:'AVC',hevc:'HEVC',av1:'AV1'}[declaredCodec]);
  else first([[/\b(?:h[ ._-]?265|x265|hevc|hev1|hvc1)\b/i,'HEVC'],[/\b(?:h[ ._-]?264|x264|avc|avc1)\b/i,'AVC'],[/\b(?:av1|av01)\b/i,'AV1'],[/\bvp9\b/i,'VP9']]);
  // Dolby Vision may legitimately also have an HDR10 fallback layer.
  if(/\b(?:dolby[ ._-]?vision|dovi|dv)\b/i.test(text))tags.push('Dolby Vision');
  first([[/\bhdr10(?:\+|plus)/i,'HDR10+'],[/\bhdr10\b/i,'HDR10'],[/\bhlg\b/i,'HLG'],[/\bhdr\b/i,'HDR'],[/\bsdr\b/i,'SDR']]);
  if(s.hdr===true && !tags.some(x=>/HDR|HLG|Dolby Vision/.test(x)))tags.push('HDR');
  if(s.hdr===false && !tags.some(x=>/HDR|HLG|Dolby Vision|SDR/.test(x)))tags.push('SDR');
  if(/\b(?:atmos|dolby[ ._-]?atmos)\b/i.test(text))tags.push('Atmos');
  first([[/\bdts[ .:_-]?x\b/i,'DTS:X'],[/\btrue[ ._-]?hd\b/i,'TrueHD'],[/\bdts[ ._-]?hd[ ._-]?ma\b/i,'DTS-HD MA'],[/\bdts[ ._-]?hd\b/i,'DTS-HD'],[/\b(?:e[ ._-]?ac[ ._-]?3|ddp|dd\+|dolby[ ._-]?digital[ ._-]?plus)/i,'DD+'],[/\b(?:ac[ ._-]?3|dd|dolby[ ._-]?digital)(?=\b|\d)/i,'Dolby Digital'],[/\bdts(?=\b|\d)/i,'DTS'],[/\baac(?=\b|\d)/i,'AAC'],[/\bflac\b/i,'FLAC'],[/\b(?:lpcm|pcm)\b/i,'PCM'],[/\bmp3\b/i,'MP3']]);
  // DDP5.1/AAC2.0 are common release spellings without a word boundary.
  first([[/(?:^|[^0-9])7\.1\b/,'7.1'],[/(?:^|[^0-9])6\.1\b/,'6.1'],[/(?:^|[^0-9])5\.1\b/,'5.1'],[/(?:^|[^0-9])2\.0\b|\bstereo\b/i,'2.0'],[/\bmono\b/i,'1.0']]);
  for(const [pattern,label]of [[/\bimax\b/i,'IMAX'],[/\bextended\b/i,'EXTENDED'],[/\bdirector'?s[ ._-]?cut\b/i,"Director's Cut"],[/\bproper\b/i,'PROPER'],[/\brepack\b/i,'REPACK'],[/\b(?:10[ ._-]?bit|hi10p)\b/i,'10bit'],[/\b12[ ._-]?bit\b/i,'12bit']])if(pattern.test(text))tags.push(label);
  if(c.langs.length>1)tags.push('MULTI AUDIO');
  return tags;
}

function createAggregator(options) {
  if (!options || typeof options.request !== 'function') throw new Error('Transport obrigatório');
  const now = options.now || Date.now;
  // Successful metadata/manifests only. No long-lived signed media URL cache.
  const cache = new Map();
  async function aggregate(rawInput,rawConfig) {
    const config = normalizeConfig(rawConfig);
    const ctx = parseInput(rawInput.id,rawInput.type,rawInput.season,rawInput.episode);
    ctx.meta=metadata({},ctx,config);
    const output = options.output || 'native';
    const started = now(), deadline = started + config.totalTimeoutMs;
    const controller = new AbortController();
    const stats = {sources:0,candidates:0,probes:0,failures:0,ageBlocked:false,elapsedMs:0};
    let closed = false, firstTimer, totalTimer;
    const winners = new Map(), fallback = new Map(), seen = new Set(), queue = [];
    let pendingSources = 0, runningProbes = 0;
    const parentSignal = rawInput.signal;
    let finish;
    const done = new Promise(resolve => {
      finish = () => {
        if (closed) return;
        closed = true; clearTimeout(firstTimer); clearTimeout(totalTimer);
        if (parentSignal) parentSignal.removeEventListener('abort',finish);
        controller.abort(); queue.length = 0;
        for (const [key,c] of fallback) if (config.allowUnverified || c.deferred) winners.set(key,c);
        stats.elapsedMs = now()-started;
        resolve({streams:selectResults([...winners.values()],config).map(c=>format(c,output,ctx.meta)),stats:Object.assign({},stats)});
      };
      totalTimer = setTimeout(finish,config.totalTimeoutMs);
    });
    if (parentSignal) {
      parentSignal.addEventListener('abort',finish,{once:true});
      if (parentSignal.aborted) finish();
    }
    if (!config.manifests.length || closed) {finish();return done;}
    async function request(url,params) {
      if (closed || now() >= deadline) throw new Error('Prazo encerrado');
      return options.request(url,Object.assign({timeoutMs:Math.min(config.requestTimeoutMs,deadline-now()),maxBytes:1048576,signal:controller.signal},params));
    }
    async function json(url,ttl) {
      const cached = cache.get(url);
      if (cached && cached.expires > now()) return cached.value;
      const response = await request(url,{});
      if (response.status <200 || response.status>=300 || response.truncated) throw new Error('Resposta inválida');
      const value = JSON.parse(response.text);
      if (!value || typeof value !== 'object') throw new Error('JSON inválido');
      if (ttl && !closed) {
        if (cache.size >= 256) cache.delete(cache.keys().next().value);
        cache.set(url,{value,expires:now()+ttl});
      }
      return value;
    }
    function accept(c,health) {
      if (closed) return;
      c.health = health;
      winners.set(c.key,c);
      if (!firstTimer) firstTimer = setTimeout(finish,config.settleMs);
    }
    function exhausted() { if (!pendingSources && !runningProbes && !queue.length) finish(); }
    function pump() {
      queue.sort((a,b)=>b.q-a.q || compare(a,b));
      while (!closed && queue.length && runningProbes<config.probeConcurrency) {
        if (stats.probes >= config.maxProbes) { queue.length=0; break; }
        const c = queue.shift();
        runningProbes++; stats.probes++;
        probe(c,config,request,now).then(h=>{
          if (h.verified) accept(c,h);
          else if (!closed) { c.health=h; fallback.set(c.key,c); }
        }).catch(()=>{ stats.failures++; }).finally(()=>{runningProbes--;pump();exhausted();});
      }
      exhausted();
    }
    function ingest(streams,source) {
      const candidates = streams.map(s=>candidate(s,source,config,output)).filter(Boolean).sort((a,b)=>b.q-a.q || compare(a,b));
      for (const c of candidates) {
        if (closed || stats.candidates>=config.maxCandidates) break;
        if (seen.has(c.key)) continue;
        seen.add(c.key); stats.candidates++;
        if (c.deferred) {
          // Native debrid delegation is an untested alternative, never a speed-tested winner.
          c.health={verified:false,method:'Nuvio/TorBox',deferred:true};
          fallback.set(c.key,c);
          if (!firstTimer) firstTimer=setTimeout(finish,config.settleMs);
        } else if (config.probeMode==='off') {
          c.health={verified:false,method:'desativado'};
          fallback.set(c.key,c);
          if (config.allowUnverified && !firstTimer) firstTimer=setTimeout(finish,config.settleMs);
        } else queue.push(c);
      }
      pump();
    }
    async function prepare() {
      const key = config.tmdbApiKey || options.tmdbApiKey || '';
      let meta = {};
      if (key) {
          const suffix='?api_key='+encodeURIComponent(key)+'&language='+encodeURIComponent(config.languages[0]||'pt-BR');
        if (!ctx.tmdbId) {
          const found=await json('https://api.themoviedb.org/3/find/'+ctx.imdbId+suffix+'&external_source=imdb_id',3600000);
          const row=((ctx.type==='movie' ? found.movie_results : found.tv_results) || [])[0];
          if (row) ctx.tmdbId=String(row.id);
        }
        if (ctx.tmdbId) {
          const type=ctx.type==='series'?'tv':'movie';
          const append=type==='movie'?'external_ids,release_dates,credits':'external_ids,content_ratings';
          meta=await json('https://api.themoviedb.org/3/'+type+'/'+ctx.tmdbId+suffix+'&append_to_response='+append,3600000);
          ctx.imdbId=ctx.imdbId || meta.imdb_id || meta.external_ids && meta.external_ids.imdb_id;
        }
      }
      ctx.meta=metadata(meta,ctx,config);
      // Primary configured language, then original language, then extra preferences.
      // The original language changes ranking only; it never proves a stream's audio.
      config.languages=[...new Set([config.languages[0],ctx.meta.originalLanguage,...config.languages.slice(1)].filter(Boolean))];
      if (!ratingAllowed(ctx.meta.ratings,config)) {stats.ageBlocked=true;return false;}
      return true;
    }
    async function sourceJob(manifestUrl) {
      try {
        const manifest=await manifestLoads.get(manifestUrl);
        if (closed) return;
        if (String(manifest.id||'').startsWith('org.kazuji.media.')) return;
        // Do not execute remote native JS manifests; HTTP stream protocol only.
        let id=streamId(ctx,'tt');
        if (!id || !supports(manifest,ctx.type,id)) id=streamId(ctx,'tmdb:');
        if (!id || !supports(manifest,ctx.type,id)) return;
        const response=await json(resourceUrl(manifestUrl,ctx.type,id),0);
        stats.sources++;
        if (Array.isArray(response.streams)) {
          const streams=response.streams.slice(0,300);
          const source=String(manifest.name || manifest.id || 'Add-on').replace(/[\r\n]+/g,' ').slice(0,100);
          // Preserve direct HTTP immediately even if the debrid API stalls.
          if(output==='native' && options.resolveStreams)ingest(streams,source);
          const resolved=options.resolveStreams?await options.resolveStreams(streams,{ctx,config,request}):streams;
          if(!closed)ingest(resolved,source);
        }
      } catch (_) {stats.failures++;}
      finally {pendingSources--;exhausted();}
    }
    // Load manifests concurrently with metadata; stream endpoints wait for the age gate.
    const manifestLoads=new Map();
    let manifestIndex=0;
    const loadTasks=config.manifests.map(url=>{
      let resolve;
      const promise=new Promise(r=>{resolve=r;});
      manifestLoads.set(url,promise);
      return async()=>{try{resolve(await json(url,600000));}catch(_){resolve(null);}};
    });
    async function manifestWorker(){while(!closed && manifestIndex<loadTasks.length)await loadTasks[manifestIndex++]();}
    for(let i=0;i<Math.min(config.sourceConcurrency,loadTasks.length);i++)manifestWorker().catch(()=>{});
    const manifestsReady = config.manifests.map(url=>()=>sourceJob(url));
    // Metadata resolution is a single gate. An unavailable rating fails closed by default.
    Promise.resolve().then(prepare).then(allowed=>{
      if (closed || !allowed) {finish();return;}
      pendingSources=manifestsReady.length;
      if (!pendingSources) {finish();return;}
      let index=0;
      async function worker() {while(!closed && index<manifestsReady.length) await manifestsReady[index++]();}
      for(let i=0;i<Math.min(config.sourceConcurrency,pendingSources);i++) worker().catch(()=>{});
    }).catch(()=>{stats.failures++;if(config.allowedRatings.length && config.unknownRating==='block'){stats.ageBlocked=true;finish();}else{
      // Without metadata, TMDB-prefixed addons can still work; never fabricate an IMDb id.
      pendingSources=manifestsReady.length;
      let index=0;
      async function worker(){while(!closed && index<manifestsReady.length) await manifestsReady[index++]();}
      for(let i=0;i<Math.min(config.sourceConcurrency,pendingSources);i++) worker().catch(()=>{});
      if(!pendingSources)finish();
    }});
    return done;
  }
  return {aggregate};
}
function compare(a,b) {
  return a.rank-b.rank || a.groupLanguage.localeCompare(b.groupLanguage) || Number(b.health && b.health.verified)-Number(a.health && a.health.verified) ||
    speed(b)-speed(a);
}
function speed(c) {return c.health && c.health.mbps>0?c.health.mbps:c.reportedMbps;}
async function probe(c,config,request,now,initialPlaylist,startedAt) {
  if (config.probeMode==='off') return {verified:false,method:'desativado'};
  const start=startedAt == null ? now() : startedAt;
  const params={headers:c.headers,timeoutMs:config.probeTimeoutMs};
  const rawRequest=request;
  request=(url,opts)=>{
    const left=config.probeTimeoutMs-(now()-start);
    if(left<=0)throw new Error('Prazo da amostra encerrado');
    return rawRequest(url,Object.assign({},opts,{timeoutMs:left}));
  };
  if (config.probeMode==='head') {
    const head=await request(c.raw.url,Object.assign({},params,{method:'HEAD',maxBytes:0}));
    if (head.status<200 || head.status>=300 || /text\/html|application\/json/i.test(head.headers['content-type'] || '')) throw new Error('Não é vídeo');
    const videoSize=head.status===200 && !/hls|dash/i.test(c.raw.type||'') && !/\.(?:m3u8|mpd)(?:[?#]|$)/i.test(c.raw.url) && !/mpegurl|dash\+xml/i.test(head.headers['content-type']||'')?positiveBytes(head.headers['content-length']):undefined;
    return {verified:false,method:'HEAD',latencyMs:now()-start,videoSize};
  }
  let url=c.raw.url;
  if (/\.mpd(?:[?#]|$)/i.test(url)) return {verified:false,method:'DASH sem amostra'};
  const hls=/\.m3u8(?:[?#]|$)/i.test(url) || /hls/i.test(c.raw.type||'');
  if (hls) {
    let playlist;
    for (let depth=0;depth<3;depth++) {
      playlist=depth===0 && initialPlaylist || await request(url,Object.assign({},params,{maxBytes:131072}));
      if (playlist.status<200 || playlist.status>=300 || playlist.truncated || !playlist.text.trim().startsWith('#EXTM3U')) throw new Error('HLS inválido');
      const lines=playlist.text.split(/\r?\n/);
      const variants=[];
      lines.forEach((line,i)=>{
        if(line.startsWith('#EXT-X-STREAM-INF:')) {
          const res=/RESOLUTION=\d+x(\d+)/i.exec(line), bw=/BANDWIDTH=(\d+)/i.exec(line);
          const path=lines.slice(i+1).find(x=>x.trim()&&!x.startsWith('#'));
          if(path)variants.push({url:resolveHttpUrl(path.trim(),playlist.url||url),height:res?Number(res[1]):0,bw:bw?Number(bw[1]):0});
        }
      });
      if(variants.length) {
        const matching=variants.filter(v=>v.height===c.q);
        if(!matching.length && variants.some(v=>v.height)) throw new Error('HLS não oferece a qualidade anunciada');
        url=(matching.length?matching:variants).sort((a,b)=>b.bw-a.bw)[0].url;
        if(!httpUrl(url))throw new Error('URL HLS inválida');
        continue;
      }
      if(lines.some(x=>x.startsWith('#EXT-X-KEY:')&&!/METHOD=NONE/.test(x))) return {verified:false,method:'HLS criptografado'};
      if(lines.some(x=>x.startsWith('#EXT-X-BYTERANGE:'))) return {verified:false,method:'HLS byte-range'};
      const segment=lines.find(x=>x.trim()&&!x.startsWith('#'));
      if(!segment)throw new Error('Sem segmento HLS');
      url=resolveHttpUrl(segment.trim(),playlist.url||url);
      if(!httpUrl(url))throw new Error('URL HLS inválida');
      break;
    }
    if (/\.m3u8(?:[?#]|$)/i.test(url)) return {verified:false,method:'HLS aninhado'};
  }
  const sampleStart=now();
  const response=await request(url,Object.assign({},params,{headers:Object.assign({},c.headers,{Range:'bytes=0-'+(config.sampleBytes-1)}),maxBytes:config.sampleBytes}));
  if (response.status!==200 && response.status!==206) throw new Error('Amostra indisponível');
  if (!hls && response.text.trim().startsWith('#EXTM3U')) {
    return probe(Object.assign({},c,{raw:Object.assign({},c.raw,{type:'hls'})}),config,rawRequest,now,response,start);
  }
  const contentType=response.headers['content-type']||'';
  if (/text\/|application\/(json|xml|.*mpegurl|dash\+xml)/i.test(contentType) || /^\s*(<!doctype|<html|\{\s*"|#EXTM3U)/i.test(response.text.slice(0,64))) throw new Error('Amostra não é mídia');
  const bytes=response.bytes && response.bytes.length || 0;
  if (bytes<32768) return {verified:false,method:'amostra pequena'};
  // Throughput is observed bytes / request + transfer time; never Content-Length / RTT.
  const elapsed=Math.max(1,now()-sampleStart), mbps=bytes*8/elapsed/1000;
  const verified=mbps>=config.minMbps[c.q];
  let videoSize;
  if(!hls){
    const range=/^bytes\s+(\d+)-(\d+)\/(\d+)$/i.exec(response.headers['content-range']||'');
    if(response.status===206 && range && Number(range[1])<=Number(range[2]) && Number(range[2])<Number(range[3]))videoSize=positiveBytes(range[3]);
    else if(response.status===200)videoSize=positiveBytes(response.headers['content-length']);
  }
  return {verified,method:'amostra',mbps,bytes,latencyMs:now()-start,slow:!verified,mediaType:hls?'hls':'direct',videoSize};
}
function format(c,output,meta) {
  const health=c.health || {verified:false};
  const q=c.q===2160?'4K':c.q ? c.q+'p':'Qualidade desconhecida';
  const bytes=streamSize(c.raw)||health.videoSize;
  const fileSize=bytes?sizeLabel(bytes):typeof c.raw.size==='string'?c.raw.size:undefined;
  const technical=fusionTags(c);
  const tag=health.verified ? health.mbps.toFixed(1)+' Mbps (amostra)' : health.deferred ? 'resolver no Nuvio · sem teste de velocidade' : health.slow ? 'abaixo da velocidade mínima' : c.reportedMbps?c.reportedMbps.toFixed(1)+' Mbps (fonte informa; não verificado)':'velocidade não verificada';
  const title=[meta.title+' ('+(meta.year||'ano não informado')+') · '+q+' · Áudio: '+(c.langs.join(', ')||'não informado')+(technical.length?' · '+technical.join(' · '):''),
    (meta.creators||'Diretor/criador não informado')+' · '+(meta.studios||'Estúdio não informado'),
    'Classificação '+meta.country+': '+(meta.ratings.join(', ')||'não informada')+' · '+tag+(fileSize?' · '+fileSize:'')+' · '+c.source].join('\n');
  const label=output==='native'?title:'Kazuji '+q+' · '+c.groupLanguage;
  if (output==='stremio') {
    const result=Object.assign({},c.raw,{name:label,title,description:title});
    result.behaviorHints=Object.assign({},c.raw.behaviorHints);
    const filename=releaseFilename(c.raw);
    if(filename)result.behaviorHints.filename=filename;
    if(bytes)result.behaviorHints.videoSize=bytes;
    if(Object.keys(c.headers).length) {result.behaviorHints.proxyHeaders=Object.assign({},result.behaviorHints.proxyHeaders,{request:c.headers});result.behaviorHints.notWebReady=true;}
    return result;
  }
  return {name:label,title,url:c.raw.url,quality:q,provider:c.source,language:c.langs.join(', ')||'Desconhecido',
    size:fileSize,type:health.mediaType || (/\.m3u8(?:[?#]|$)/i.test(c.raw.url)?'hls':'direct'),headers:c.headers,
    subtitles:(Array.isArray(c.raw.subtitles)?c.raw.subtitles:[]).filter(s=>httpUrl(s.url)).map(s=>({url:s.url,language:s.lang || s.language || 'und',name:s.name,headers:safeHeaders(s.headers)}))};
}
module.exports={DEFAULTS,normalizeConfig,createAggregator,quality,audioLanguages,supports,resourceUrl,ratingAllowed,parseInput,resolveHttpUrl,candidate};

const KAZUJI_QUALITY_PROFILE={"id":"4k","name":"4K","quality":2160,"enabled":true};
'use strict';
// Appended to aggregator.js by scripts/build.js; no external require at runtime.
const KazujiCore = module.exports;
const QUALITY_PROFILE = typeof KAZUJI_QUALITY_PROFILE==='undefined'?null:KAZUJI_QUALITY_PROFILE;
const QUALITY_OPTIONS = [[2160,'4K'],[1080,'1080p'],[720,'720p'],[480,'480p'],[0,'Qualidade desconhecida']];

function baseQualities(settings) {
  // Preserve legacy text/preset selections when new toggles have not been saved.
  return KazujiCore.normalizeConfig({qualities:settings.qualities}).qualities;
}

function nativeTransport(maxConcurrent) {
  let active=0;
  const waiting=[];
  function drain() {
    while(active<maxConcurrent && waiting.length) {
      const job=waiting.shift();
      if(job.signal && job.signal.aborted){job.reject(new Error('Cancelado'));continue;}
      active++;job.resolve();
    }
  }
  return async function request(url,options) {
    const signal=options.signal;
    let timer, abortHandler;
    const work=(async()=>{
      await new Promise((resolve,reject)=>{waiting.push({resolve,reject,signal});drain();});
      try {
        if(signal && signal.aborted)throw new Error('Cancelado');
        const response=await fetch(url,{method:options.method||'GET',headers:options.headers||{},body:options.body,signal});
        const headers={};
        for(const key of ['content-type','content-range','content-length','accept-ranges','location']) headers[key]=response.headers.get(key)||'';
        const bytes=new Uint8Array(await response.arrayBuffer());
        const text=await response.text();
        return {status:response.status,url:response.url||url,headers,bytes:bytes.subarray(0,options.maxBytes),text,
          truncated:bytes.length>options.maxBytes || /\n\.\.\.\[truncated\]$/.test(text)};
      } finally {active--;drain();}
    })();
    // Nuvio currently ignores fetch's signal; keep the physical slot until fetch settles.
    // A timeout only stops awaiting it. QuickJS evaluation can still wait for all
    // native jobs before the app receives getStreams' result; this is not a hard deadline.
    const timeout=new Promise((_,reject)=>{
      timer=setTimeout(()=>reject(new Error('Tempo excedido')),options.timeoutMs);
      if(signal){abortHandler=()=>reject(new Error('Cancelado'));signal.addEventListener('abort',abortHandler);if(signal.aborted)abortHandler();}
    });
    try{return await Promise.race([work,timeout]);}
    finally{clearTimeout(timer);if(signal && abortHandler)signal.removeEventListener('abort',abortHandler);}
  };
}

async function getStreams(tmdbId,mediaType,season,episode) {
  if(typeof setTimeout!=='function' || typeof clearTimeout!=='function'){
    console.warn('[Kazuji] Runtime sem timers assíncronos. No Mobile, atualize para Full 0.5.4-beta ou runtime compatível. No TV, use a versão HTTP.');
    return [];
  }
  const settings=Object.assign({},QUALITY_PROFILE?{resultMode:'all',maxCandidates:96}:{},globalThis.KAZUJI_DEFAULT_CONFIG||{},globalThis.SCRAPER_SETTINGS||{});
  if(!QUALITY_PROFILE && QUALITY_OPTIONS.some(([q])=>settings['quality'+q]!=null)){
    const previous=baseQualities(settings);
    settings.qualities=QUALITY_OPTIONS.filter(([q])=>{
      const value=settings['quality'+q];
      return value==null?previous.includes(q):value===true || value==='true';
    }).map(([q])=>q);
  }
  if(settings.advancedJson){
    const extra=JSON.parse(settings.advancedJson);
    if(!extra || typeof extra!=='object' || Array.isArray(extra))throw new Error('Configuração avançada inválida');
    Object.assign(settings,extra);
  }
  // Video requests can keep Nuvio's native evaluation alive until its timeout.
  // Apply after presets, saved settings and advanced JSON so old values cannot
  // re-enable sampling/HEAD or suppress all links as unverified.
  settings.probeMode='off';
  settings.allowUnverified=true;
  const torboxApiKey=String(settings.torboxApiKey||'').trim();
  if(torboxApiKey){
    if(settings.totalTimeoutMs==null || settings.totalTimeoutMs==='')settings.totalTimeoutMs=12000;
    if(settings.settleMs==null || settings.settleMs==='')settings.settleMs=2500;
  }
  // A quality supplier cannot be widened by stale toggles or advanced settings.
  if(QUALITY_PROFILE)settings.qualities=[QUALITY_PROFILE.quality];
  const config=KazujiCore.normalizeConfig(KazujiCatalog.applySources(settings,KazujiCore.normalizeConfig));
  const resolveStreams=torboxApiKey?KazujiTorBox.createResolver({apiKey:torboxApiKey,quality:KazujiCore.quality,
    eligible:(stream,current)=>!!KazujiCore.candidate(stream,'TorBox',{...current,torrentMode:'native'},'stremio'),
    maxResolutions:settings.torboxMaxResolutions,warn:message=>console.warn('[Kazuji] '+message)}):null;
  const engine=KazujiCore.createAggregator({request:nativeTransport(config.sourceConcurrency+1),output:'native',tmdbApiKey:globalThis.TMDB_API_KEY||'',resolveStreams});
  const result=await engine.aggregate({id:String(tmdbId),type:mediaType,season,episode},config);
  console.info('[Kazuji] '+JSON.stringify(result.stats));
  return result.streams;
}

function onSettings() {
  function select(key,label,values,defaultValue,description){return{type:'select',key,label,description,defaultValue,options:values.map(x=>({label:x[0],value:x[1]}))};}
  function text(key,label,placeholder,description){return{type:'text',key,label,placeholder,description};}
  const selected=QUALITY_PROFILE?[QUALITY_PROFILE.quality]:baseQualities(Object.assign({},globalThis.KAZUJI_DEFAULT_CONFIG||{},globalThis.SCRAPER_SETTINGS||{}));
  return [
    {type:'header',label:QUALITY_PROFILE?'Kazuji · '+QUALITY_PROFILE.name:'Kazuji · Agregador'},
    ...(QUALITY_PROFILE?[{type:'info',label:'Este fornecedor retorna somente '+QUALITY_PROFILE.name+'. As fontes já estão embutidas. Preencha a chave TorBox abaixo para resolver hashes em cache. Não exige servidor Kazuji.'}]:[]),
    text('torboxApiKey','TorBox · API key','','Chave da sua conta TorBox. Consulta cache e devolve links HTTP de vídeo. É salva pelo Nuvio nas configurações deste fornecedor, não publicada no GitHub. O formulário do app usa campo de texto.'),
    text('torboxMaxResolutions','TorBox · máximo de torrents em cache por busca','4','Padrão 4, máximo 12, por fornecedor. Só registra itens já em cache; não inicia downloads de torrents sem cache.'),
    {type:'info',label:'Emblemas Fusion preparados automaticamente. Importe https://joaovpimenta.github.io/kazuji-media/badges.json em Nuvio → Configurações → Streams → URLs de emblemas Fusion. No plugin JS, o tamanho conhecido aparece como texto; o emblema de tamanho precisa do add-on HTTP.'},
    {type:'info',label:typeof setTimeout==='function' && typeof clearTimeout==='function'
      ? 'Requer Nuvio Mobile Full 0.5.4-beta ou runtime compatível. Consulta manifestos e metadados em paralelo, sem testar ou baixar vídeos. Ordena por qualidade, idioma e velocidade informada pela fonte, quando disponível. A reprodução confirma a disponibilidade do link.'
      : 'Este runtime não oferece os timers exigidos. No Mobile, atualize para Nuvio Full 0.5.4-beta ou runtime compatível. No TV, use o add-on HTTP Kazuji.'},
    {type:'toggle',key:'useBuiltInSources',label:'Usar catálogo de fontes embutidas',defaultValue:true},
    text('manifests','Manifestos adicionais / TorBox','https://addon.exemplo/configuracao/manifest.json','Separe URLs por vírgula, ou use um array JSON. Use o manifesto gerado com TorBox no add-on original. Soma às fontes embutidas; URLs repetidas são consultadas uma vez. Configurações são individuais por fornecedor.'),
    ...(!QUALITY_PROFILE?[{type:'header',label:'Qualidades de vídeo · selecione uma ou mais'},
      ...QUALITY_OPTIONS.map(([q,label])=>({type:'toggle',key:'quality'+q,label,defaultValue:selected.includes(q)}))]:[]),
    text('languages','Idioma principal e preferências extras','pt-BR','Configure o idioma do aparelho manualmente (padrão pt-BR). A ordem será: primeiro idioma, idioma original da obra no TMDB, depois os demais. Legendas não comprovam áudio.'),
    select('resultMode','Agrupamento dos resultados',[['Por qualidade e idioma','per_language'],['Por qualidade','per_quality'],['Todas as fontes válidas','all']],QUALITY_PROFILE?'all':'per_language'),
    text('resultsPerGroup','Fontes por grupo','1','De 1 a 20; padrão 1. Ignorado em Todas as fontes válidas. Áudio múltiplo entra no grupo de maior preferência, sem duplicar a URL.'),
    select('languageMode','Filtro de idioma',[['Preferir','prefer'],['Somente preferências e idioma original','strict'],['Qualquer idioma, sem preferência','any']],'prefer'),
    {type:'toggle',key:'allowUnknownLanguage',label:'Aceitar áudio sem idioma informado',defaultValue:true},
    text('allowedCodecs','Codecs permitidos','h264,hevc,av1','Vazio aceita todos. Configure conforme seu aparelho. Usa apenas informações declaradas pela fonte; não detecta capacidades do dispositivo.'),
    select('hdrMode','Compatibilidade HDR',[['Qualquer formato','any'],['Somente SDR','sdr'],['Excluir Dolby Vision','no_dolby_vision']],'any'),
    {type:'toggle',key:'allowUnknownCompatibility',label:'Aceitar codec/HDR não informado',defaultValue:true,description:'Aplica-se quando um filtro de codec/HDR está ativo.'},
    text('allowedRatings','Classificações permitidas','L,10,12','Vazio desativa o filtro. Use os códigos do país escolhido. Padrão BR: L,10,12,14,16,18. Bloqueia todo o título quando não permitido.'),
    text('country','País da classificação','BR','Código ISO: BR, US, GB, etc. Padrão BR.'),
    select('unknownRating','Título sem classificação',[['Bloquear','block'],['Permitir','allow']],'block','Aplicado quando há classificações permitidas configuradas.'),
    text('totalTimeoutMs','Prazo de seleção (ms)','6500','De 500 a 20000 ms; inclui TMDB e fontes. O runtime do app pode aguardar requisições pendentes além desse prazo.'),
    text('settleMs','Janela após primeira fonte (ms)','650','0 para concluir a seleção imediatamente; maior dá chance a outros idiomas/qualidades.'),
    text('advancedJson','Configuração avançada JSON','{"sourceConcurrency":4,"maxCandidates":96}',QUALITY_PROFILE?'Ajustes descritos no README. A qualidade deste fornecedor é fixa. Testes de vídeo permanecem desativados.':'Ajustes descritos no README. Se definir qualities aqui, prevalece sobre os botões. Testes de vídeo permanecem desativados.'),
    {type:'info',label:'Aceita links HTTP de vídeo de qualquer fonte, inclusive TorBox/outros debrid. Com a chave acima, resolve hashes em cache diretamente na API TorBox. A chave global do Nuvio não é importada automaticamente. Usa TMDB_API_KEY do app para metadados.'},
    {type:'header',label:'Fontes embutidas · ativação e manifestos configurados'},
    {type:'info',label:'URLs configuradas substituem o manifesto público da respectiva fonte. Preencher uma URL ativa a fonte por padrão; um botão salvo como desativado prevalece. Fontes sem configuração e manifestos indisponíveis não impedem as demais.'},
    ...KazujiCatalog.sources.flatMap(source=>[
      {type:'toggle',key:'sourceEnabled_'+source.id,label:source.name,defaultValue:source.enabled || source.kind!=='direct',description:source.kind==='direct'?'Fonte HTTP pública; URL personalizada opcional.':source.kind==='torrent'?'Ativa com sua chave TorBox; aceita também manifesto personalizado com links HTTP.':'Ativa depois de preencher o manifesto configurado no add-on original. A chave TorBox não substitui o login/configuração exigido pela fonte.'},
      text('sourceManifest_'+source.id,source.name+' · manifesto configurado','https://addon/configuracao/manifest.json','Configuração: '+source.url+' · Opcional para fontes públicas. Use a URL completa do manifesto; não a página /configure.'),
    ]),
  ];
}
module.exports={getStreams,onSettings};
