'use strict';
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.resolve(__dirname,'..');
const source=['// Generated by npm run build. Edit src/aggregator.js and src/provider.js.\n',
  fs.readFileSync(path.join(root,'src/aggregator.js'),'utf8'),'\n',fs.readFileSync(path.join(root,'src/provider.js'),'utf8')].join('');
new vm.Script(source,{filename:'kazuji.js'});
const file=path.join(root,'providers/kazuji.js');
if(process.argv.includes('--check')){
  if(!fs.existsSync(file)||fs.readFileSync(file,'utf8')!==source)throw new Error('Bundle desatualizado: execute npm run build');
}else fs.writeFileSync(file,source);
console.log('Bundle Nuvio: '+Buffer.byteLength(source)+' bytes');
