'use strict';
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.resolve(__dirname,'..');
const {profiles}=require('../src/sources');
const version=require('../package.json').version;
const checking=process.argv.includes('--check');
const shared=['sources','torbox','aggregator'].map(name=>fs.readFileSync(path.join(root,'src',name+'.js'),'utf8')).join('\n');
const adapter=fs.readFileSync(path.join(root,'src/provider.js'),'utf8');
const banner='// Generated by npm run build. Edit src/ and scripts/build.js.\n';
function write(relative,source){
  const file=path.join(root,relative);
  if(checking){
    if(!fs.existsSync(file)||fs.readFileSync(file,'utf8')!==source)throw new Error('Arquivo gerado desatualizado: '+relative+'; execute npm run build');
  }else{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,source);}
}
function bundle(relative,profile){
  const source=banner+shared+'\n'+(profile?'const KAZUJI_QUALITY_PROFILE='+JSON.stringify(profile)+';\n':'')+adapter;
  new vm.Script(source,{filename:relative});write(relative,source);
}
function scraper(profile,filename){return{
  id:'kazuji-'+profile.id,name:profile.name,version,filename,supportedTypes:['movie','tv'],enabled:profile.enabled,hasSettings:true,
  description:'Fontes embutidas · '+profile.name+'. Links HTTP e TorBox em cache com sua API key. Nuvio Mobile Full 0.5.4-beta ou runtime compatível.',
  supportsExternalPlayer:true,logo:'https://joaovpimenta.github.io/kazuji-media/assets/logo.svg',
};}
const json=value=>JSON.stringify(value,null,2)+'\n';
const repository=scrapers=>({name:'Kazuji Media',version,description:'Fontes embutidas, TorBox e fornecedores separados por qualidade.',author:'joaovpimenta',scrapers});
bundle('providers/kazuji.js');
const scrapers=[];
for(const profile of profiles){
  const filename='qualities/'+profile.id+'/provider.js';
  bundle(filename,profile);scrapers.push(scraper(profile,filename));
  // The standalone manifest and provider are colocated, so Nuvio's loader
  // requires neither absolute URLs nor parent-path normalization.
  write('qualities/'+profile.id+'/manifest.json',json(repository([scraper(profile,'provider.js')])));
}
write('manifest.json',json(repository(scrapers)));
write('legacy/manifest.json',json(repository([{...scrapers[0],id:'kazuji-media',name:'Kazuji Media',enabled:true,filename:'provider.js'}])));
bundle('legacy/provider.js');
console.log('Nuvio: '+profiles.length+' fornecedores, manifestos individuais e plugin legado verificados.');
